name: 'dev-ops-pipeline'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  move-to-sandbox: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jupiterbak/ayx-server-deploy@v4
        with:
          ayx-server-api-url: 'http://ec2-18-184-0-23.eu-central-1.compute.amazonaws.com/webapi/'
          ayx-server-client-id: '8DD8BBF92DAD13469d0e6fa6b5c4e8c1d1f980e130842b7718b95a4f17664860816fffabe5860de'
          ayx-server-client-secret: '4d2571855980947fee7917480a2903dba8fb4bcdd3500fb95c85013549888e1e'
          ayx-user-mail: 'jupiter.bakakeu@gmail.com'
          folder-to-sync: './'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
            overwrite: true
            path: |
              *.tgz
              server-sync-results.json
  Test-results: # with the data configuration execute all alteryx tests
    needs: move-to-sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Data
        uses: actions/checkout@v2.4.2
        with:
          ref: 'main'
      - name: Read Data Configuration
        uses: juliangruber/read-file-action@v1.1.4
        id: package
        with:
          path: './Report.json'
      - name: Execute Alteryx Tests
        uses: jupiterbak/ayx-test-reporter@v1.0.2
        with:
          ayx-server-api-url: 'http://ec2-18-184-0-23.eu-central-1.compute.amazonaws.com/webapi/'
          ayx-server-client-id: '8DD8BBF92DAD13469d0e6fa6b5c4e8c1d1f980e130842b7718b95a4f17664860816fffabe5860de'
          ayx-server-client-secret: '4d2571855980947fee7917480a2903dba8fb4bcdd3500fb95c85013549888e1e'
          collection-to-test: '00_Data_Ingestion'
          args: "${{ steps.package.outputs.content }}"
      - name: Upload the Test Results
        uses: actions/upload-artifact@v4
        with:
            overwrite: true
            path: |
              *.tgz
              results.json
      - name: Generate a Mocha Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()    
        with:
          name: Data Ingestion Test Results            
          path: results.json            
          reporter: mocha-json
          fail-on-error: false
